### ISSUE TITLE
Notification timeout

### ISSUE THREAD

**Issue by ghost** [JFreegman/toxic#570]
I use notification-daemon dunst [https://github.com/dunst-project/dunst/](dunst)  @bebehei @tsipinakis
and he have functional
Notification timeout 0 to prevent important work email notifications from disappearing until you manually dismiss them.

## Why need this?
It is easy to miss the notification, while you step away from the pc. 
this setting helps you not to hide important notifications. 

## Problems
But if i try update config dunstrc for appname toxic use timeout 0 
That new message notifications disappears always after 3 seconds.

```
[toxic]
    timeout = 0
    appname = toxic
    urgency = critical
    background="#FFFFFF"
    foreground = "#000000"
````

And it should leave notification while it is not closed in manual. 

i check dbus-monitor and see

```
method call time=1618915235.310239 sender=:1.10 -> destination=:1.2 serial=63 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "toxic"
   uint32 0
   string ""
   string "NAME"
   string "TEXT"
   array [
   ]
   array [
   ]
   int32 3000
error time=1618915235.310410 sender=org.freedesktop.DBus -> destination=:1.10 error_name=org.freedesktop.DBus.Error.ServiceUnknown reply_serial=63
   string "The name :1.2 was not provided by any .service files"
```
if i right understand in default timeout 3000
   **int32 3000**

if use other  notification  

```
method call time=1618942102.916375 sender=:1.960 -> destination=:1.898 serial=6 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=GetServerInformation
method return time=1618942102.917447 sender=:1.898 -> destination=:1.960 serial=209 reply_serial=6
   string "dunst"
   string "knopwob"
   string "1.5.0 (2020-07-23)"
   string "1.2"
method call time=1618942102.918820 sender=:1.960 -> destination=:1.898 serial=7 path=/org/freedesktop/Notifications; interface=org.freedesktop.Notifications; member=Notify
   string "notify-send"
   uint32 0
   string ""
   string "a"
   string ""
   array [
   ]
   array [
      dict entry(
         string "urgency"
         variant             byte 1
      )
   ]
   int32 -1
```
**default ->    int32 -1**

or this 

```
array [
      dict entry(
         string "urgency"
         variant             byte 1
      )
```
Add dunst -print

``` 
  {
        appname: 'toxic'
        summary: 'username'
        body: 'test message'
        icon: 'dialog-information'
        raw_icon set: false
        icon_id: '(null)'
        desktop_entry: ''
        category: 
        timeout: 0
        urgency: CRITICAL
        transient: 0
        formatted: '<b>username </b>
test message'
        fg: #000000
        bg: #00FFFF
        highlight: #1745d1
        frame: #888888
        fullscreen: show
        progress: -1
        stack_tag: 
        id: 5
        actions: {}
        script_count: 0
}
```

Perhaps this is the reason that the settings are not applied or maybe the problem is in (dunst) notification-daemon.
